---
name: make test

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        perl: ["5.40", "5.20", "5.8"]
        exclude:
          - os: "windows-latest"
            perl: "5.8"
      fail-fast: false
    env:
      MAKECMD: ${{ (matrix.os == 'windows-latest' && matrix.perl == '5.20' && 'dmake') || (matrix.os == 'windows-latest' && 'gmake') || 'make' }}
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
          distribution: ${{ matrix.os == 'windows-latest' && 'strawberry' || 'default' }}
      - run: |
          touch cpanfile
          echo 'requires "Net::CIDR::Lite" => "0";' >> cpanfile
          echo 'requires "Socket" => "0";' >> cpanfile
          echo 'requires "Socket6" => "0";' >> cpanfile
          echo 'requires "Test::More" => "0.88";' >> cpanfile
          echo 'requires "Test::Pod" => "1.00";' >> cpanfile
          echo 'requires "version" => "0";' >> cpanfile
      - run: cpanm --insecure --installdeps .
      - run: perl Makefile.PL
      - run: ${{ env.MAKECMD }}
      - run: ${{ env.MAKECMD }} test TEST_VERBOSE=1
